### PR TITLE
Bootsrap framebuffers will always work

### PR DESCRIPTION
**Pull request by dark-samus**

### CODE REVIEW

**Comment by d0k3** [comment]
Just had a look, and it looks like this would also require some changes to draw.h, right? Also, I see we have screenbuffers for left and right screen now, but since D9 is 2D - which one is used normally?

**Comment by dark-samus** [comment]
@d0k3 no changes to draw.h required, everything is set properly and works just fine as-is... 
the framebuffers for left and right are actually set to the same address (but the actual registers that are being set control the left and right sides, so they're labeled a bit differently... you can see in fb.h this:

 #define FB_TOP_LEFT 0x18300000
 #define FB_TOP_RIGHT 0x18300000

**Comment by dark-samus** [comment]
@d0k3 OK, well I've been told by mid-kid that this isn't a good idea, and after some discussion he convinced me... anyways, I do have a way to do it, and I'll be adding it when I get around to it

**Comment by d0k3** [comment]
Alright, closing this for now

**Pull request closed without merging**
