### PR TITLE
Silence -Wpedantic warning

### PR DESCRIPTION
**Pull request by einstein95**

### CODE REVIEW

**Comment by d0k3** [comment]
A description would help.

**Comment by einstein95** [comment]
There's nothing really to describe. All it does is silence the compiler warning:
```
Decrypt9WIP/source/theme.c:69:0: warning: ISO C forbids an empty translation unit [-Wpedantic]
 #endif
 ^
```

**Comment by d0k3** [comment]
That's somewhat of a messy fix for this problem. stdio.h is already included via "common.h" (which is included in "theme.h"). I'll think about it. Thanks!

**Comment by d0k3** [comment]
Okay, I changed it a little and merged it. Thank you!

**Pull request closed without merging**
