### PR TITLE
Add NDS dumping features

### PR DESCRIPTION
**Pull request by idgrepthat**
Mostly osilloscorpion's (deleted account) work with a couple touches
from myself.

### CODE REVIEW

**Comment by d0k3** [comment]
Great! Thankyou! I will just take a quick look and merge this after.

**Comment by d0k3** [comment]
Okay... there are merge conflicts, mainly this does not contain certain stuff from my latest commits, or even removes it again. I will need to resolve these conflicts, which might take some time.

**Comment by idgrepthat** [comment]
You'd probably add a separate option for NTR dumping. Dump CIA from a DS game might get noobs too excited. 

edit: oh really?  Hmm. It said there was no conflicts from my end :/

**Comment by ihaveamac** [comment]
it seems to be based off a slightly older D9 commit, since it's re-adding things like `Zerokey crypto is not supported here` and removes the metadata creation for CIAs

**Comment by d0k3** [comment]
Okay, I'm trying to fix this myself now. idgrepthat, you will be credited, and osiloscorpion will, too.

**Comment by d0k3** [comment]
Okay, I basically fixed this commit up via WinMerge (my ndsdump branch). Now, we've got a problem. I can't attribute the commit to osilloscorpion, cause his account is gone. Next choice would be to attribute it to idgrepthat, but for that I'd need your email, @idgrepthat (cause git forces me to provide it)

@idgrepthat - it's your choice. Give me your email adress and the commit will be attributed to you. Alternatively, I can just keep myself as commit author and credit you both in the commit comment.

**Comment by idgrepthat** [comment]
The latter is good enough :)

**Comment by d0k3** [comment]
Alright, closing this then. I took everything new out of this pull request and did the commit myself. @idgrepthat and osilloscorpion credited. Thanks everyone involved!

**Pull request closed without merging**
