### PR TITLE
fix fb for a9lh

### PR DESCRIPTION
**Pull request by Cpasjuste**
Hi D0k3,

This allow loading the bootstrap binary from either a9lh or Brahma like loaders.

### CODE REVIEW

**Comment by d0k3** [comment]
Sorry, that took a bit. The framebuffer works! Question, though, will that break bootstrap comaptibility? I don't mind much if it does, but I should know.

Also, could you perhaps squash the two commits into one?

**Comment by d0k3** [comment]
Merged! I'd still be interested in bootstrap compatibility, maybe you know something.

**Comment by Cpasjuste** [comment]
At least it works with Brahma loader. Is it the question ?

**Comment by d0k3** [comment]
No, I meant this:
https://github.com/shinyquagsire23/bootstrap

This is a precursor of Brahma, and thats why the build goal is called bootstrap. If you don't know, nevermind. I do not either and no one uses this anymore :).

**Pull request merged**
